### ISSUE TITLE
Fails to install, serial port error

### ISSUE THREAD

**Issue by DEA156** [yungsters/homebridge-urtsi#1]
When I try to install I get "Failed at serialport@2.1.2 install script" error.

**Comment by DEA156** [comment]
OK, I was able to fix this on my own. This is what I did:
1. I used NPM to install the newest version of serialport.
2. I made a local copy of homebridge-urtsi by copying the code from GitHub and pasting it into a blank document using the text editor nano.
3. I used nano to delete the dependency for serialport from package.json in my local copy of homebridge-urtsi. (I did this because yungsters' version of package.json specifies an old version of serialport.)
4. I used NPM to install my local copy of homebridge-urtsi.
5. I also installed a local copy of node-urtsi.
6. After installation of homebridge-urtsi and node-urtsi, homebridge was unable to locate the components belonging to node-urtsi, so I had to change "const urtsi = require('urtsi')" to specify the exact path to urtsi.js on my Raspberry Pi.
7. Now homebridge was able to launch homebridge-urtsi, but I got an error message that "serialport is not a constructor" when I tried to activate a shade. I fixed this by removing ".serialPort" from "const SerialPort = require('serialport').SerialPort" at the top of urtsi.js in the node-urtsi package.

With homebridge-urtsi the shades appear in Homekit as window coverings and respond to Siri commands. Due to limitations with the Somfy remote system, the only positions are up, down, and "middle" (also known as the favorite or stop position). "Middle" may not actually be 50% if your favorite/stop position is different.

How it works:
1. Tell Siri to open the shade --> shade opens as expected.
2. Tell Siri to close the shade --> shade closes as expected.
3. Tell Siri to go to any position between top and bottom --> shade goes to the favorite or stop position. If the Somfy shade is programmed to have the stop position at 33%, that is the only position between 0% and 100% you can get. Tell Siri to go to 50%, you get 33%.
4. Works great with groups of shades.

Yungsters, thank you so much for writing this code!!!!

**Comment by yungsters** [comment]
Look a like the main request here is to upgrade the `serialport` dependency for `node-urtsi`, is that right?

I no longer have this device, but I can help update this dependency (and update call sites) if that will help make your’s and others’ lives easier.

**Comment by yungsters** [comment]
https://github.com/yungsters/homebridge-urtsi/commit/fa1616234ba998b50c83206faecf36a8a6c4a2f0 should fix this.

**Comment by DEA156** [comment]
Yungsters, can you update the serialport dependency again? Node-urtsi calls for v6.2.2 of serialport, but this causes homebridge-urtsi to fail installation.
